# Get base SDK Image from Microsoft

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build-env
WORKDIR /app

# Copy the CSPROJ file and restore any dependecies (via NUGET)

COPY *.csproj ./
RUN dotnet restore

# Copy the project files and build our own release
COPY . ./
ENV ASPNETCORE_ENVIRONMENT=Development
RUN dotnet publish -c release -o out
# Generate runtime release
FROM mcr.microsoft.com/dotnet/aspnet:5.0 
WORKDIR /app
EXPOSE 80
COPY --from=build-env /app/out .
ENTRYPOINT [ "dotnet" ,"API.dll"]